# CHAPTER I

# Basic Operations and Control
&copy; Harishankar Manikantan, maintained on GitHub at [hmanikantan/ECH60](https://github.com/hmanikantan/ECH60) and published under an [MIT license](https://github.com/hmanikantan/ECH60/blob/master/LICENSE).

Return to [Course Home Page](https://hmanikantan.github.io/ECH60/)

**[(1.1) Data Types and Basic Operations](#intro)**
* [Integers](#int)
* [Floats](#float)
* [Strings](#string)
* [Tuples](#tuples)
* [Lists](#lists)
* [Numbers and math: Numpy](#numpy)

**[(1.2) User-defined Functions](#functions) <br>**
* [Defining functions](#func)
* [Single-line lambda functions](#lambda)

**[(1.3) Logic and Repetition](#structure)<br>**
* [The IF condition](#if)
* [The FOR and WHILE loops](#loops)

**[(1.4) Vectorization: Manipulating Scientific Data](#vector)**
*  [Introduction to arrays](#arrays) <br>
*  [Sequences](#sequences) <br>
*  [Slicing](#slicing) <br>
*  [Vectorizing](#vectorizing) <br>

**[(1.5) Formatting and Storing Data](#format)**
*  [Formatting output](#output) <br>
*  [Storing arrays](#storing) <br>

**[Practice problems](#exer)**


<a id='intro'></a>


## (1.1) Data Types and Basic Operations

All computer languages allow for data to be stored in named variables. It is important to understand the type of the stored data. The basic and most commonly used data types are:

<a id='int'></a>


### Integer 
any integer quantity. e.g. 2,-10,146, ...

Try assigning an integer value to the variable `a` in the code cell below. Simply type `a=2` or `a=-10` or any other integer you wish and run it (hit `shift+enter`). To check if that assignment was successful, type `print(a)` or just `a` in the second code box and run it: Python will display the stored value. Try again. These values are stored in memory througout this notebook unless you redefine it.

In [1]:
# assign an integer to b
a=-12 

In [2]:
# show what value is stored in b
print(a)

-12


Note: the `#` sign is useful to write comments in code. Comments are text that python does not read. It's good practice to comment your code so others know what's happening.

An important difference in code as compared to normal mathematics is that `a=1` doesn't represent a statement of equality, but instead is a statement of assignment. What you're telling the computer is to evaluate the right-hand-side, and assign that value to the left hand side. This means that the equivalent mathematical statement `1=a` will give you an error in Python (and in most coding languages). Try it...

This also means that you can reassign numbers quite easily. For example, a common code line you will learn to use in the coming weeks is `a=a+1` which makes no sense mathematically. But, in code, this means that you evaluate the RHS using the previously stored value of the variable `a`, and then assign that as the new value of `a`. Try it ... (make sure you have run the very first code cell so `a` has an initial value. You would get an error otherwise. Try to force the error by typing `b=b+1` instead...)

In [3]:
a = a + 1
print(a)

-11


In fact, this line is so common in python that a shortcut usage is simply `a+ = 1`. Try this above ...

<a id='float'></a>


### Float 
'floating point' quantities or 'floats' indicate that a decimal point 'floats' somewhere in between the digits. This is probably the most common data type we will use to solve engineering problems. All real numbers are floats: 24.56, -11.7884, 146.0, ... etc. You could also define floats using the exponential notation with an `e`, which is just a convenineent way of saying shift the decimal places to the right or left. For example, the float 134.64 is equivalent to 1.3464e2, and 0.00078 is equivalent to 7.8e-4.

Try assigning any float to `b`, and then see what `b` has stored. You can run both these lines of code at once.

In [4]:
# assign a float
b=124e-4

# then show what b is
print(b)

0.0124


Python conveniently changes an integer to a float if necessary. For example, multiplying the integer `a` and the float `b` from before automatically makes the result a float. You can execute multiple lines of code at once.

In [5]:
# assign an integer
a=2

# assign a float
b=34.57

# multiply a and b and store answer in c
c=a*b

# display c
print(c)

69.14


You can also define floats using the `float()` command. In fact, you can do arithmetic inside the brackets of the `float()` command. Try various arithmetic operations here (`+` to add, `-` to subtract, `*` to multiply, and `/` to divide):

In [6]:
# define and simultaneously display a float using the float() command
print(float(-2.421312*4.0))

-9.685248


To raise a number to a certain power, use `**`. So `2**3` should return 8. Try it...

In [7]:
2**5

32

Finally, you can convert a float to an integer using the `int()` command. However, note that this simply removes everything to the right of the decimal place without correctly rounding the real number:

In [8]:
print(int(-19.76))

-19


You can also define multiple variables in one line:

In [9]:
a,b,c = 5, 13.87, -16

<a id='string'></a>



### String

A string is a set of characters, like a name or a word or numbers or some combination that you want to store as it is. Use quotes to define strings:

In [10]:
str_1='Davis'
str_2='California'
str_3='95616'

You can perform string operations such as concatanation (fancy word for 'adding' words or text) or display additional text along with variables as follows:

In [11]:
# save str_1 followed by space followed by str_2 to str_4
str_4=str_1+' '+str_2

# show str_4 followed by the word ZIP followed by str_3
print(str_4+' ZIP '+str_3)

Davis California ZIP 95616


You can also select or manipulate parts of a string. Always remember that Python starts counting from 0, not 1. So the variable `str_1` has index numbers 0, 1, 2, 3, and 4 corresponding to D, a, v, i, and s. So `str_1[0]` should give D, and `str_1[3]` should give i, and so on. You can select a sequence of characters from a string by providing the range. Here, note that Python syntax is such that `str_1[m:n]` includes characters from index m until but not including index n. Try this out with `str_1` and `str_2` so you get comfortable.

In [12]:
# slice str_2 from index number 4 (included) to index number 6 (not included)
print(str_2[4:6])

fo


<a id='tuples'></a>


### Tuples 

Tuples are sequences of different kinds of data. Tuples are pretty handy in some contexts and database management, where you might have numeric data mixed with string data. Tuple are defined with the format `tuplename=('data1', 'data2', ...)`. Note the use of brackets and quotes. For example, my office is in room 3114 in Bainer, and I could store this information as 

In [13]:
# create a tuple names office with a sequence of a string, an integer, and another string
office=('Bainer',3114,'UC Davis')

The benefit of tuples is that you can then access individual items as `variable1, variable2, ... = tuplename`, or equivalently using `tuplename[index in sequence starting from 0]`. For example:

In [14]:
# assign the three elements to new variables named building, room, and location
building, room, location = office

# display room number as part of a sentence
#print('My office room number is:',room)

# use index to retrieve data
print('My office is in',office[0],'hall in', office[2])

My office is in Bainer hall in UC Davis


Not the use of commas between data and text. You would get an error if you ignore the commas. Try it.


You can create a tuple within a tuple within a tuple and so on .... an inception of tuples!! It's all about the ordering of the brackets and the commas. For example:

In [15]:
birth_data=(('Albert','Einstein',('March',14,1879)),('Marie','Curie',('November',7,1867)))

creates a tuple of two sub-tuples. Each sub-tuple contains a sequence of a string (first name), another string (last name), and a sub-sub-tuple containing a string (birth month), an integer (birth day) and another integer (birth year). So `birth_data[0]` refers to the subtuple with Einstein's data, `birth_data[0][2]` refers to the subsubtuple with Einstein's full birthday, and `birth_data[0][2][2]` gives Einstein's birth year. Always remember Python starts counting indices at 0, not 1.

From this, you could extract and display things like:

In [16]:
print(birth_data[0][1],'was born',birth_data[0][2][2]-birth_data[1][2][2], 'years after', birth_data[1][1])

Einstein was born 12 years after Curie


Change the birth_data tuple to include a third person's information, and play around with displaying sentences like the example above by modiying the code. Remember to hit `shift+enter` after each update of a code cell.

<a id='lists'></a>



### Lists

Lists are like tuples but are mutable, meaning they can be edited, appended, and data can be added or deleted from within the list. A tuple on the other hand is immutable. The difference in the definition of a list is the use of a square bracket:

In [17]:
# list of five integers
a = [0, -1, 3, 8, 9]
print('a is',a) 

# empty list
b = []
print('b is',b)

# repeated list
print('a repeated three times is',3*a)

a is [0, -1, 3, 8, 9]
b is []
a repeated three times is [0, -1, 3, 8, 9, 0, -1, 3, 8, 9, 0, -1, 3, 8, 9]


You can access the 3rd value of `a` using `a[2]` (python starts counting from 0), or the first from the end using `a[-1]`. What about `a[-2]`? Try various index calls below:

In [18]:
a[2]

3

We will learn about more complicated and useful 'slicing' techniques next week.

Now we can manipulate the list names address using

`listname.insert(position,data to insert)` to insert at a specific point OR

`listname.append(data to insert)` to append at the end OR

`listname[position]=[new data]` to replace data at specific location(s)

This 'dot notation' is fairly common in Python and we will see a lot more of it. Try the following and change location and data type to get a sense of the manipulations:

In [19]:
# define a list
address = ['davis', 95616]
print('original list:',address)

# insert at position 1
address.insert(1,'CA')
print('modified list:',address)

original list: ['davis', 95616]
modified list: ['davis', 'CA', 95616]


In [20]:
# define a list
address = ['davis', 95616]
print('original list:',address)

# append to end
address.append('USA')
print('modified list:',address)

original list: ['davis', 95616]
modified list: ['davis', 95616, 'USA']


In [44]:
# define a list
address = ['davis', 95616]
print('original list:',address)

# modify specific index range
address[0:1]=['Davis', 'CA']
print('modified list:',address)

original list: ['davis', 95616]
modified list: ['Davis', 'CA', 95616]


<a id='numpy'></a>


### Numbers and Math: `numpy`

We have seen so far that python has the basic arithmetic operation (addition,subtraction, multiplication, division, power). For most involved problems, we will need much more than that. Through this quarter, we will learn to work with matrices and vectors, trigonometric functions, exponentials and more specialized operations.

Python has a large community of developers who have created and perfected entire 'libraries' of these useful functions organized into 'modules'. To use any such module, we import them using the command `import modulename`. One of the most common modules is `numpy`, short for NUMerical PYthon. Import it by running (`shift+enter`) the following:

In [28]:
import numpy

You will then have access to all the functions in the `numpy` module (there are 100s of common math operations and functions in numpy. You can get a full list by running `dir(numpy)` after importing it). Common ones include `sqrt`, `exp`,`log`,`log10`,`sin` (and all trigs), `arcsin` (and all inverse trigs), irrational numbers like $\pi$ (as `pi`) and $e$ (as `exp`), and many more common mathematical operations. After importing `numpy`, try evaluating the square root of 2 by typing `sqrt(2)` here...

You should see an error saying sqrt is not defined! That's because the `sqrt` function 'belongs' to the imported numpy module, and the correct way to tell python that is `numpy.sqrt(2)`. Try this above...

This is an important theme across python. Dots represent a connection between the module or variable to the left and a subfunction or a property to the right.

You can avoid having to use a rather length `numpy.sqrt(2)` everytime by specifically importing the `sqrt` function from `numpy` as follows, so you can simply use `sqrt(2)` etc...

In [29]:
from numpy import sqrt
sqrt(2)

1.4142135623730951

But then if you need another operation, like the exponential (using the `numpy` function `exp`), you need to import that separately using `from numpy import exp`, and so on. Or, you could import all functions from `numpy` in one go by running `from numpy import *`. The asterisk is a 'wildcard' which means import everything.

While this last form of importing a module seems convenient, things can get confusing as you advance in python if two different modules have functions that are identically named. The compromise, and the accepted standard among most python users, is to give `numpy` (or any module that you import) a nickname. A common nickname for `numpy` is `np`, so the import line as subsequent usage would be

In [2]:
import numpy as np
[np.sqrt(2),
np.exp(10),
np.log(22),
np.log10(22),
np.pi]

[1.4142135623730951,
 22026.465794806718,
 3.091042453358316,
 1.3424226808222062,
 3.141592653589793]

This nickname can be useful when the module (or submodule) name is rather long. For example, another common module that we will encounter next week is `matplotlib.pyplot` which is commonly abbreviated to `plt` in the import line.

Finally, you can read the help text associated with any python command by typing `help(print)` or `help(import)` etc. For module specific help file, type `numpy.info(numpy.sin)` etc.


<a id='functions'></a>


## (1.2) User-defined Functions

<a id='func'></a>


Functions are handy snippets of code you can create to do a short set of operations. Python has tons of inbuilt functions: for example, `sqrt()` from `numpy` is an inbuilt function that perfroms a commonly used mathematical operation. User-defined functions allow us to have named operators like `sqrt` programmed to do a specific set of user-defined calculations on demand

### Defining functions

In python, functions are coded as follows:

In [22]:
def trianglearea(base,height): # base and height are input variables
    area=0.5*base*height # do calculations using input variable
    return area # return the variable named area

The colon after the first line is important. So is the indent of one tab space for every line of code that belongs to that function.

Once you have run this code, the function `trianglearea` can be called at any point with the input parameters in the same order, and it will give you the area as the result:

In [23]:
a=trianglearea(6,10)
print(a)

30.0


A function can contain multiple lines of calculations. And it can return multiple variables. For example, a useful common calculation in engineering is going back and forth between the temperature units of Celsius, Fahrenheit, and Kelvin. The following function is written such that an input in F is converted to both C and K:

In [24]:
def FtoCandK(fahr):
    cels=(fahr-32)*5/9
    kelv=cels+273
    return cels,kelv

Note that `FtoCandK` as written has two return varibles, and so calling it gives two outputs:

In [25]:
print(FtoCandK(100))

(37.77777777777778, 310.77777777777777)


You can even directly assign the two to different variables when you call the function:

In [26]:
tempC, tempK = FtoCandK(70)
print(tempC)
print(tempK)

21.11111111111111
294.1111111111111


As another example, conside the following mathematical function:

$$f(x)=\cos\left(\frac{e^{-x}-1}{x-1} \right),$$ 

which becomes the following python code:

In [5]:
import numpy as np

def myfunc(x):
    f=np.exp(-x)-1
    f=f/(x-1)
    f=np.cos(f)
    return f

Note that python first evaluates the RHS and then assigns that result to the LHS when we run the line `f=f/(x-1)`. This lines looks mathematically inconsistent (in math, we would cancel the `f` on both side!!), but is perfectly sensible in code. And the same thing again in the third line inside the function: python first evaluates the cosine using the current value of `f` on the RHS, and then assigns or rewrites `f` on the LHS with the new value.

Evaluating `myfunc` now gives us the value of $f(x)$ for any $x$...

In [32]:
myfunc(2)

0.6488952617067709

<a id='lambda'></a>



### Single-line `lambda` Functions

Another shortcut version of functions are `lambda` functions. These are best-suited for single-line short functions, and follows the format: `functionname = lambda input:calculation`.

In [27]:
FtoC = lambda fahr:(fahr-32)*5/9

FtoC(96.8)

36.0

Lambda functions work for multiple inputs too -- just separated then with commas:

In [46]:
tri_area = lambda base,height: 0.5*base*height

tri_area(5,10)

25.0

<a id='structure'></a>


## (1.4) Logic and Repetition

So far, we have seen how to define or assign variables (numbers, strings, tuples, ...) and functions. The real power of coding lies in its ability quickly manipulate these quantities algorithmic logic and automation. We will start with the essential building blocks of algorithm development: the `if` condition and the `for` and `while` loops.

<a id='if'></a>



### The `if` condition

The `if` statement and its variants are ubiquitous across every programming language, and helps you design logical algorithmic 'branches'. For example, this snippet of code checks the value of the variable named `cost`, and creates two 'branches' depending on the value of `cost` and `cash`:

In [33]:
cost = 7
cash = 10
if cost <= cash:
    print('You may buy this burrito')
else: 
    print('Sorry, you need more cash')

You may buy this burrito


Try running the above code for different values of `cost` and `cash` variables. 

The syntax of the `if` statement is as follows: the `if` is followed by a 'conditional' or a logic operation ("Is the cost less than or equal to cash?"). If the answer is YES (or TRUE, in logic terminology), then that branch is executed and we get a burrito. If the answer is NO (or FALSE), then the other branch corresponding to the `else` line is executed. Note the colon after the `if` and `else` lines. Also, we don't need to have an `else` statement if you don't need that second branch: a code with just the `if` branch will work just fine.

You can make more branches with more carefull logical comparisons. For example:

In [34]:
cost = 6
cash = 10
if cost < cash:
    change = cash - cost
    print('You may buy this burrito and you get back', change, 'dollars')
elif cost == cash: 
    print('You have exact change!')
else:
    print('Sorry, you need more cash')

You may buy this burrito and you get back 4 dollars


Here, we have introduced an `elif` line. So python first checks the first `if` ("is cost less than cash?") an executes is if TRUE. Only if that line is FALSE does python check the `elif` line ("is cost exactly equal to cash"). And only if both `if` and `elif` are false will the else be executed. You can have multiple `elif` branches for more involved comparisons.

The order is important. Which means a `<=` comparison in `if` above would never run the `elif` case. Try it. Rationalize why that is the case.

Importantly, note that the 'equal to' comparison is `==`. This is a common thing to get wrong for first-time coders: a simple `=` is an assignment, meaning python takes the RHS and rights that to the LHS. A logical comparison like `if` or `elif` is NOT an _assigment_ but a _comparison_ , and the way to let python know this is by using the `==`.

A common comparison is 'not equal to', given by `!=`. So `if cost != 7:` would only be true if `cost` is any value but `7`. 

Another useful comparison operator is 'divisible by', written as `%`. So `if cost %2 == 0:` would be true only for even numbers.



<a id='loops'></a>



### The `for` and `while` loops

Automation is the best part of coding, and loops are the simplest form of repeating a set of operations as desired. The `for` loops simply repeats a set of code for the conditions that are specified after the `for` statement. Let's say you wanted the square root of odd integers from 1 to 10.

In [35]:
import numpy as np

for i in range(1,11,2):
    print('square root of', i,'is',np.sqrt(i))

square root of 1 is 1.0
square root of 3 is 1.7320508075688772
square root of 5 is 2.23606797749979
square root of 7 is 2.6457513110645907
square root of 9 is 3.0


Here, `range(start,end+1,step)` is an in-built python function that returns values of the 'loop index' variable `i`. Range can handle integer start, end, and step sizes. In the above example, 1 is included, 11 is not included, and the step size is 2. So the values of `i` that run the loop are 1,3,5,7,9. How would you do even numbers between 0 and 10? Try it above...

What if you needed non-integers to run the loops. Then you use `np.arange` instead. Same logic. Try this to generate square roots of 1, 1.2, 1.4, ..., 4.6, 4.8, 5 in the code above.

You can format the output to make it look neat. Let's say we want ot only show the first two decimal places in the output. Try using `print('square root of', i,'is %4.2f' % np.sqrt(i))` instead of the print line above. This `%` sign tells python that the `np.sqrt(i)` output should be foramtted as a float (that's the f) that's 4 characters wide (including the decimal point) with 2 characters after the point. Try combinations like `%6.2f` or `%4.3f` etc.

Periodic reminder that blocks of code (for functions, conditionals, loops, ...) all are defined by the indentation. And the colon after the first line. Be very careful to use this format.

What if you need to run a loop but do not know at the beginning of the code how many loops may be required? In other words, what if you didn't know the 'end-point' of `i` above. For instance, let's say for whatever reason that I want to determine square roots of integers until the square root value is 3.6. The `while` loop is better suited for this

In [36]:
i=1
while(np.sqrt(i) <= 3.6):
    print('square root of', i,'is', np.sqrt(i))
    i+=1

square root of 1 is 1.0
square root of 2 is 1.4142135623730951
square root of 3 is 1.7320508075688772
square root of 4 is 2.0
square root of 5 is 2.23606797749979
square root of 6 is 2.449489742783178
square root of 7 is 2.6457513110645907
square root of 8 is 2.8284271247461903
square root of 9 is 3.0
square root of 10 is 3.1622776601683795
square root of 11 is 3.3166247903554
square root of 12 is 3.4641016151377544


We couldn't have done it this easily with a `for` loop because we didn't know when we started that we needed to get to `i=12` before we meet our condition. The `while` loop runs until that condition is not satistied.

On the flip side, the `while` loop does not increment automatically like the `for` loop: notice how we need to explicitly use `i+=1` (short hand for `i=i+1`) within the `while`. This also means that we must 'initialize' the value of `i` before entering the loop because otherwise python would know what `i` is the first time around.

As you begin writing code, be wary of 'infinite loops'. If the conditions you wrote are always true, the loop could go on for ever. In such cases, hit `Ctrl+C` to terminate your code and reexamine what went wrong.

Finally, you can you shorthand versions of `for` with the `range` function to create lists (remember the square brackets) of numbers easily:

In [37]:
[i for i in range(0,10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

You can even bring in `if` conditions in this form to create more specific lists. E.g. a list of the squares of odd numbers between 0 and 30:

In [38]:
[x**2 for x in range(0,30) if x%2 != 0]

[1, 9, 25, 49, 81, 121, 169, 225, 289, 361, 441, 529, 625, 729, 841]

Almost all solutions you will develop in this course will involve inserting `if` and related statements into loops, or having both conditionals and loops in functions. As an example, consider the Fibonacci series that appears in a variety of natural patterns (flower petal arrangements, pineapple patterns, artichoke petals, .... look it up). Each new number in the series is the sum of the last two (starts as 0,1,1,2,3,..). Algorithmically, if we call `a` and `b` as the previous and current numbers, then the new number is `c=b+a`. A quick way of getting the first 10 numbers is, without even introducing a new variable `c`, is:

In [39]:
a=0
b=1
print(a)
print(b)
for i in range(3,10+1):
    b+=a
    a=b-a
    print(b)

0
1
1
2
3
5
8
13
21
34


Think about the logic behind the `b+=a` and `a=b-a` lines. There are many ways to do this calculation. Can you think of others?

Now, if I wanted a function that takes in `n` and spits out the n-th Fibonacci number, and I wanted my function to be well-commented and fool-proof (what if someone entered a negative value of n?), it would look something like this. Study each line, and think of what it does. Also watch the indenting associated with each group of code (python automatically indents, but it's good practice to watch when you code).

In [40]:
# function fibo(n) takes in a positive integer n and returns the nth fibonacci number starting at 0
def fibo(n):
    a=0    # initial 'previous' number
    b=1    # initial 'current' number
    if n<1:       # branch corresponding to n=0 or smaller
        print('provide n that is greater than 0')
    elif n==1:      # branch corresponding to n=1
        return 0  # fibo(1) returns 0
    elif n==2:    # branch corresponding to n=2
        return 1  # fibo(2) returns 1
    else:         # branch corresponding to n=3 and beyond
        for i in range(3,n+1):   # range includes 3, and runs until n, doesn't include n+1 
            b+=a   # new 'current' number as sum of old current and previous
            a=b-a  # redefine new 'previous' number
        return b

If you understand every line above, run it and then run `fibo(n)` for different values of `n` (including negative numbers) and see what you get...

In [41]:
fibo(10)

34

You can also do opreations directy on the n-th Fibonacci number. For example, if you need the ratio of the 20th Fibonacci number with the 19th number, you would just type `fibo(20)/fibo(19)` etc. See exercise problem 6.


Alternatively, you can use python's 'object-oriented' approach to storing values. This means that lists are stored as 'objects' on which you can perform operations like `append` using the dot operator. If you wanted to generate a list of N fibonacci numbers, the following code is more succinct and elegant. 

In [42]:
# function to generate a list that contains first N fibonnaci numbers
# does not check for negative n etc: we can add all that like above

def fibo_list(n):
    fibo_list=[0,1,1]
    for i in range(n-3):
        fibo_list.append(fibo_list[-1]+fibo_list[-2])
    return fibo_list

Recall that `fibo_list[-k]` is the k-th entry from the end. Running `fibo_list(n)` generates a list:

In [43]:
fibo_list(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

Lists, however, are not ideal for mathematical operations like vector-matrix calculations. We will then need the `array` data type that we will see next week.

<a id='vector'></a>

## (2.1) Vectorization: Manipulating Scientific Data

Perhaps the most useful and convenient data type for engineering and mathematical calculations is an `array`. Unlike lists and tuples, we can do mathematical operations on arrays. They are therefore particularly well-suited for representing force vectors, position vectors, scalar information at different point in space (like mass, concentration, ...), and pretty much any variable in an engineering problem. 

<a id='arrays'></a>


### The `array` type
Arrays are part of numpy so remember to import numpy first.

In [1]:
import numpy as np

Any list filled with numbers can be turned into a numpy array by using `np.array(listname)`:

In [2]:
mylist=[1.4,4.5,-9.5,23.8]
myarray=np.array(mylist)
print('mylist is',mylist)
print('myarray is',myarray)

mylist is [1.4, 4.5, -9.5, 23.8]
myarray is [ 1.4  4.5 -9.5 23.8]


Although this might seems identical, they are extremely different data structures. For example, `2*mylist` corresponds to the action of repeating the list twice (we saw this in week 1). This operation is callled concatanation:

In [3]:
2*mylist

[1.4, 4.5, -9.5, 23.8, 1.4, 4.5, -9.5, 23.8]

However, `2*myarray` does the mathematical operation of multiplying each element in the array by the number 2:

In [4]:
2*myarray

array([  2.8,   9. , -19. ,  47.6])

You can directly fill an array (without needing a list first) by directly entering numbers in `np.array([])` :

In [5]:
mynewarray=np.array([3.2, 4.5, 5.9])
print(mynewarray)

[3.2 4.5 5.9]


By extension, filling up a matrix (or a 2D array) requires two sets of square brackets: one set for each row, and an outer set of square brackets around the entire array (and a final parenthesis so python understands where to start and stop):

In [6]:
mymatrix=np.array([[1, 4, 5],[6, -9, 11],[0, 23, 1]])
print(mymatrix)

[[ 1  4  5]
 [ 6 -9 11]
 [ 0 23  1]]


Numpy has many useful predefined matrix arrays. For example, `np.zeros` gives an array filled with zeros

In [7]:
np.zeros(3)

array([0., 0., 0.])

For 2D arrays (or matrices) with m rows and n columns filled with zeros, use `np.zeros((m,n))`. Try this above...

Similarly, arrays filled with all entries equal to $1$ are easily obtained by `np.ones`:

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Check what `np.ones(3)` returns. And `np.eye(n)` gives the square identity matrix with n rows and n columns:

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Note that `np.array([a,b])` is simply a vector, and is neither a row nor a column in the linear algebra sense. If you need to specify shape, use `np.array([[a,b]])` for a $1\times 2$ matrix (or a row vector) and `np.array([[a],[b]])` for a $2\times 1$ matrix (or a column vector). And you can go back and forth between row and column vectors using `np.transpose()`. Python doesn't differentiate between a row or a column vector unless you explicitly make the array a matrix.

In [10]:
myrow=np.array([[1,2]])
mycolumn=np.array([[3],[4]])
print('row vector :\n',myrow) #the \n within a string indicates a newline
print('transpose of row vector :\n',np.transpose(myrow))
print('column vector :\n',mycolumn)
print('transpose of column vector :\n',np.transpose(mycolumn))

row vector :
 [[1 2]]
transpose of row vector :
 [[1]
 [2]]
column vector :
 [[3]
 [4]]
transpose of column vector :
 [[3 4]]


Matrix algebra is then straightforward. Consider the vectors $a$ and $b$, and matrix $M$ as follows: $$a=\begin{bmatrix}-4 & 5 \end{bmatrix}, \quad b=\begin{bmatrix}3 & 2\end{bmatrix}, \quad M=\begin{bmatrix}5 & -3\\2 & 4\end{bmatrix}.$$ In python code, we would define them as 

In [11]:
a=np.array([-4,5])
b=np.array([3,2])       
M=np.array([[5,-3],[2,4]])

The rules of linear algebra apply, which means you could add any two arrays of the same shape. Try `a+b` or `b-a` etc above. 

We can perform the 'dot product' (or inner product or scalar product) of any two vectors, given by $a\cdot b = a_1 b_1 + a_2 b_2$. You could do this operation by running a loop, or much more efficiently use numpy's vectorized operation `dot`:

In [12]:
np.dot(a,b)

-2

Try changing the numbers in $a$ and $b$ (try making them 3-element vectors!) to convince yourself this works. You could do `np.sqrt(np.dot(a,a))` to get the magnitude of vector `a` in one shot... try it!


Similarly, the 'outer product' (or dyadic product or tensor product) of two vector would give a matrix: $a\otimes b = \begin{bmatrix}a_1b_1 & a_1 b_2 \\ a_2b_1 & a_2b_2 \end{bmatrix}$.<br> In numpy, the outer product is simply:

In [13]:
np.outer(a,b)

array([[-12,  -8],
       [ 15,  10]])

Note that the order of operation matter: unlike the dot product, the outer product is not commutative. Check how `np.outer(a,b)` and `np.outer(b,a)` are related (and recall if this is consistent linear algebra...).

Finally, one of the more important matrix operations we will do in solving linear equations in engineering problems is matrix-matrix and matrix-vector multiplication. Calculate by hand what you expect for the 'post-multiplication' $M\cdot a$ or $M\cdot b$, the 'pre-multiplication' $a\cdot M$ or $b\cdot M$, and the matrix-matrix product $M\cdot M$. All of these are `dot` operations in numpy, and evaluate each below to see if you get consistent results:

In [14]:
np.dot(M,a)

array([-35,  12])

Numpy has a host of linear algebra tools we will use when we need to solve equations in a couple of weeks. Details can be looked up as required at the [online numpy manual](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html). Remember: when in doubt, look up in an online manual or just google it. The point of this course is not to memorize the syntax but to get comfortable using them in problems later on. Some of these functions are within the linear algebra submodule `linalg` of numpy. For example, calculating the matrix inverse or determinant require the `linalg.inv` or `linalg.det` function inside numpy so they should be used as:

In [15]:
np.linalg.inv(M)

array([[ 0.15384615,  0.11538462],
       [-0.07692308,  0.19230769]])

We will come back to matrix inverses and linear systems soon.

You can also generate arrays of size m x n filled with random numbers between 0 an 1 using `np.random.random((m,n))`. Or an m x n array filled with a normal (Gaussian) distribution of random numbers with mean p and standard deviation q using `np.random.normal(p,q,(m,n))`. Or a random integer between a and b (b not included) using `np.random.randint(a,b,(m,n))`. In the latter two cases, not providing `(m,n)` returns a single value instead of an array:

In [16]:
np.random.normal(0,10,(3,4))

array([[ 1.82686576,  0.57673658, -9.09903001, -3.65028136],
       [ 7.98806125,  2.36369392,  1.03494242, -5.53259057],
       [-0.63210839,  0.84778625, 20.29652871,  0.42793548]])

<a id='sequences'></a>


### Generating sequences

We will frequently need to generate evenly spaced numbers in a specified range when we start solving equations and doing numerical calculus later on. We already saw `np.arange` in week one, and a similar function is `np.linspace`.

`np.arange(start,end,increment)` generates a first entry equal to `start`, the next entry equal to `start`+`increment`, and so on, adding the `increment` to obtain the next value until the `end` is reached. __The end value is not included in the array__. Try different combinations below:

In [17]:
np.arange(5.1,8.6,0.8)

array([5.1, 5.9, 6.7, 7.5, 8.3])

The default `start` is $0$, and the default `increment` is $1$. So these two entries are optional. With only two arguments, `arange` assumes that the increment is $1$. With only one argument, `arange` assumes that the start is $0$ _and_ the `increment` is $1$. Try `np.arange(5,15)` and `np.arange(15)` to get a sense of how this works:

In [18]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In some application, we might not know the _size of the increment_ between each consecutive point, but we might know the _number of increments_. This is when `linspace` becomes useful.

`np.linspace(start,end,N)` generates `N` equally spaced points between `start` and `end`. __The end value is  included in the array__. And `N` defaults to 50 elements if not specified. Try different combinations below:

In [19]:
np.linspace(5.1,8.6,5)

array([5.1  , 5.975, 6.85 , 7.725, 8.6  ])

When you need you compute values of a function or expression over a range, `np.linspace` is the appropriate function as it allows you to exactly control the start and end points. When the exact spacing between consecutive points is important, `np.arange` is the better option.

What if you wanted to control both the end points _and_ the increment? We will need a lot of this in numerical calculus later on. In such case, explicitly define the start, end, and the increment, and use `arange` with a careful correction on the end argument (because end is not included in `arange` by default):

In [20]:
start=10
end=12
space=0.2
np.arange(start,end+space,space)

array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ])

<a id='slicing'></a>

### Accessing and slicing array elements


Each entry in an array has an 'index' corresponding to its position from the left (if a row) and from the top (if a column). Multidimensional arrays have multiple indices: a matrix has a row number and column number for each entry. __Always remember that python starts counting indices from 0__. And you access that element using square brackets:

In [21]:
myarray=np.array([3,5,9,7]) # array indices are 0, 1, 2, 3
myarray[2]  # retrive entry with index 2 (or third entry)

9

The idea is the same for matrices (or three- or four- dimensional arrays...):

In [22]:
myarray=np.array([[3,5,9,7],[6,-5,8,3],[1,0,9,6]])   # row indices are 0, 1, 2 and column indices 0, 1, 2, 3
myarray[1,2]   # retrive entry at row index 1 (second row) and column index 2 (or third column)

8

Extracting multiple values at the same time is called __slicing__, and you do this using the syntax `arrayname[start:end:stride]`. This is kind of like the `arange` definition except here the numbers you provide are the _indices_ within the array, and therefore can only be whole numbers. The end point is not included. The stride is optional, and defaults to 1 if not provided (and the second colon may also be omitted if the stride is not specified). 

The start defaults to 0 (the first entry) if not provided. The end defaults to the index of the last entry of the array if not provided. Not specifying either and only providing a colon like `arrayname[:]` will extract the whole array.

So, slicing the first 10 entries (index 0 through index 9) of an array named `myarray` can be done via `myarray[0:10:1]`, or simply `myarray[:10:]`, or even more simply `myarray[:10]` as the start and stride are the default anyway and the last colon can be omitted if stride is the default 1:

In [23]:
myarray=np.arange(11,31)  # array containing numbers 11 through 30
myarray[:10] # slice first 10 entries

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

You could similarly slice every third element (`myarray[::3]`), every element from index 4 onwards (`myarray[4::]`) or more complicated slices like every third element from 5th (index 4) to 15th (index 14, but remember end is not included so use 15 if you need this element too) using `myarray[4:15:3]`, etc. Try these combinations to familiarize yourself with slicing **(remember again that python indices start at 0)**:

In [24]:
myarray[4:14:3]

array([15, 18, 21, 24])

Finally, matrices can be sliced using the same logic. To extract the second and third entries (column indices 1 through 3, 3 not included) in the first row (row index 0) of a matrix `A`, you could use `A[0,1:3]`. For all entries in the third column, you could use `A[:,2]`. Try both...

In [25]:
A=np.array([[3,5,9,7],[6,-5,8,3],[1,0,9,6]])
A[0,1:3]

array([5, 9])

<a id='vectorizing'></a>

### Vectorizing


Now that we know how to generate sequences of numbers, we can start performing mathematical operations on these sequences. Let's say we want to see what the exponential function $e^x$ looks like between 0 and 1. A straightforward way to do this is to run a loop to generate numbers between 0 and 1, and then perform the exponential operation for each element. Something like this:

In [26]:
for x in np.arange(0,1,0.2):   # run a loop for x from 0 to 1 in steps of 0.2
    y=np.exp(x)   # exponentiate each element of x term-by-term
    print(y)

1.0
1.2214027581601699
1.4918246976412703
1.822118800390509
2.225540928492468


While this will give you the correct answer, python and numpy allows you to _vectorize_ your code, meaning that you can perform most operations on entire arrays of numbers. This means we can do the following:

In [27]:
x=np.arange(0,1,0.2)   # create an array of 20 entries from 0 to 5
y=np.exp(x)   # exponentiate entire array at once
print(y)

[1.         1.22140276 1.4918247  1.8221188  2.22554093]


The same applies to `sin`, `cos`, `log`, `sqrt`, multiplication/addition/division by a constant, raising to a power etc: each of these operations act on every term of the array separately. Try `np.sin(x)` or `np.sqrt(x)` or `3*x**2+5` or any similar operation....

In [28]:
3*x**2+5

array([5.  , 5.12, 5.48, 6.08, 6.92])

While this might seem like just running a `for` loop behind-the-scenes through the elements of `x`, vectorized operations are faster beacause the back-end is optmized to do these operations much better than a loop we would normally write.

<a id='format'></a>

## (1.5) Formatting and Storing Data

We now know how to manipulate numbers, vectors, and matrices using python: but how do we present them as an output in a preferred manner? For example, consider the following line of code designed to display the result of a calculation as part of a sentence:

In [30]:
a=np.exp(-np.pi)
b=np.exp(np.pi)
print('exp(-pi) is',a,'and exp(pi) is ',b)

exp(-pi) is 0.04321391826377226 and exp(pi) is  23.140692632779267


Often, we want to display only the first $N$ significant digits. Or we might need the output in exponential notation. Or a line break between the two outputs. Better yet, we might need to export numbers/matrices/datasets we generate in python in a specific format to share with other users or software. The following sections illustrate the basics of formatting rules and storing/retrieving data.

<a id='output'></a>

### Formatting output

The basic strategy for formatting output is to provide a 'placeholder' that contains information about the type of output we need. The syntax for the placeholder is `%[width].[precision][type]`, where `[type]` decides if the output is a rounded integer, a float, or in exponent notation etc. For example, use `d` for integers:

In [24]:
print('exp(-pi) is %d'%a)
print('exp(pi) is %d'%b)

exp(-pi) is 0
exp(-pi) is 23


The `%` connects the variable to the corresponding placeholder. Note there is no comma between the string and the variable when written this way. In fact, it is possible to provide multiple variables as a tuple at once:

In [31]:
print('exp(-pi) is %d and exp(pi) is %d' %(a,b))

exp(-pi) is 0 and exp(pi) is 23


Of course, both `a` and `b` here are floats, and a more appropriate `[type]` is `f`. By default formatted floats display 6 significant digits after the decimal point:

In [32]:
print('exp(-pi) is %f and exp(pi) is %f' %(a,b))

exp(-pi) is 0.043214 and exp(pi) is 23.140693


We can tune this display using `[width]` and `[precision]`. `[width]` is the total number of output characters and `[precision]` is the number of significant digits following the decimal point. The decimal point itself counts as one character: it's important to account for this when we decide `[precision]` for a desired output.

In [40]:
print('exp(-pi) is %8.4f and exp(pi) is %8.4f' %(a,b))

exp(-pi) is   0.0432 and exp(pi) is 023.1407


Written this way, both `a` and `b` are given 8 'slots' to be displayed, of which one is taken by the decimal point, and only 4 significant digits are allowed. Which means there are 3 slots left for the integer part of each variable and that leads to the extra white space in the display. We can pad this gap with zeros (use `%08.4`), left align the output (use `%-8.4`), or exactly calculate the required number of slots as needed (use `%6.4` for `a` and `%7.4` for `b`). Try each of these for the desired output. 

Exponential notation follows the same idea: just use `e` or `E` for `[type]`:

In [47]:
print('exp(-pi) is %6.4e and exp(pi) is %7.4E' %(a,b))

exp(-pi) is 4.3214e-02 and exp(pi) is 2.3141E+01


For long display outputs, `\t` or `\n` within the output string introduces a tab or return:

In [51]:
print('exp(-pi) is %6.4f \nexp(pi) is %7.4f' %(a,b))

exp(-pi) is 0.0432 
exp(pi) is 23.1407


<a id='storing'></a>

### Storing data

Every variable you define in a notebook are 'alive' only as long as the notebook is open. The code remains saved but the numbers you assign to variables are lost when you close the file. So how do we store data generated by running a code for later use or to export to some other document or to share with people?

Arrays are easily saved on your computer using the `np.save("filename",arrayname)` command. This saves a file with extension .npy in the same folder as your notebook file. Later, if you wish to load the data into another file or another python code, use `newarrayname=np.load("filename.npy")`, and the variable `newarrayname` will load that data.

The .npy format is very efficient for storage and takes very little memory on your computer. However, it can only be read by python. If you wanted something that's 'human-readable', meaning something that you could double-click and read on a device that doesn't have python (or if you want to share data with a colleague), you can instead save in the .txt or .csv (comma separated values) or .tsv (tab separated values) formats. In these cases, use `np.savetxt("filename.txt",arrayname, delimiter=",")` or `np.savetxt("filename.csv",arrayname, delimiter=",")` or `np.savetxt("filename.csv",arrayname, delimiter="\t")`, respectively. The `delimiter` tells python to put a comma or a tab space after each entry so other programs (like Excel or text editors) can recognize individual entries easily. And you can load these files via `newarrayname=np.loadtxt("filename.csv", delimiter=",")` etc.

Try the save features below. Store the matrix A in .npy, .txt, and .csv formats. Compare the file sizes in your directory. Try opening the .csv or .txt files using non-python programs (like text editors, Excel etc).

In [29]:
A=np.array([[3213,55656,93423,73424],[6245,-5455,886,3207],[19345,4460,-952,6668]])

# uncomment and run any of the following to save in different formats

np.savetxt("A_matrix.csv", A, delimiter=",")
#np.savetxt("A_matrix.txt", A, delimiter=",")
#np.save("A_matrix",A)

These files are stored on your computer even after you close this notebook. You can retrive the stored value into a new variable B as follows:

In [3]:
B=np.loadtxt("A_matrix.csv", delimiter=",")
print(B)

[[ 3213. 55656. 93423. 73424.]
 [ 6245. -5455.   886.  3207.]
 [19345.  4460.  -952.  6668.]]


`np.loadtxt` allows more extraction with specific datatype, for example, using a `dtype='str'` argument in the `loadtxt` command. Similarly, we can skip rows or selectively extract columns using the `usecols` and `skiprows` arguments. For example, `np.loadtxt("filename.csv", delimiter=',',dtype='str', usecols=[2],skiprows=2)` would load data type string from the third column only and it would skip the first 2 rows. Many more careful loading manipulations are possible using other arguments; for details, look in the [numpy loadtxt documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html).

<a id='exer'></a>





## Practice problems

(1) The solutions of the quadratic equation $a x^2 + b x +c =0$ are given by 

$$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}.$$ 

Write a python function that `quadratic_soln(a,b,c)` which returns the solution given $a$, $b$, and $c$.

Also write a single-line `lambda` function `quadratic_soln_single(a,b,c)` to only return the bigger root given the quadratic coefficients.

(2) Write a function `sphere(r)` that takes in the radius and spits out two outputs: the volume and the surface are of a sphere with radius $r$.

(3) Write a function `myfunc(x)` that will take the the input $x$, check if it's a positive number, and run a loop to add up the square roots from $0$ to $x$ if it's positive, and return the sum.

(4) The Taylor series expansion for the exponential function is 

$$e^x=\sum_{i=0}^\infty \frac{x^i}{i!} = 1+x+\frac{x^2}{2}+\frac{x^3}{6}+\ldots$$ 

If $x$ is small, a few terms are sufficient to get a good approximation. Write a function that takes $x$ as input and returns the Taylor series approximation for 10 terms. See how good this approximation is compared to the actual value of the exponential (obtained directly via `np.exp(x)`) for $x=0.1$, $0.5$, and $1$. How does this error change if we only sum to the first 3 terms in the series approximation?

Factorial is implement as `np.math.factorial(i)`... always google or look up numpy documentation online for help when you are unsure of syntax. Our goal is not to memorize syntax but to be able to develop algorithms and apply the code.

(5) Same as (2) but for the $\sin(x)$ function: 

$$\sin(x)=\sum_{i=0}^{\infty} (-1)^{i}~\frac{x^{2i+1}}{(2i+1)!} = x-\frac{x^3}{6}+\frac{x^5}{120} -\ldots$$

(6) Modify `quadratic_soln(a,b,c)` in (1) to check if the solutions are negative, and return only the positive solutions. 

(7) You can use the previously defined `fibo(n)` to do operations like adding the 10th and 20th Fibonacci directly: try `fibo(10)+fibo(20)`. A curious property of the Fibonacci sequence is that the ratio of the (n+1)th number to the n-th number approaches the golden ratio (1.61803...) as n is large!

Write a loop that evaluate the ratio of a Fibonacci number with the previous Fibonacci number until the ratio is within one millionth of a decimal point (0.000001) of the golden ratio, formally defined as 

$$\phi=\frac{1+\sqrt{5}}{2}.$$

Would you use a `for` or a `while` loop? Why? How many numbers into the sequence does the ratio coverge to within a millionth of a decimal point of $\phi$?

Hint: You might consider using the absolute value function `abs()` ...

(8) Create a 2D array to represent the following matrix using a nested loop (a loop within a loop):
$$\begin{bmatrix} 4 & 8 & 12 & 16 & 20\\6 & 12 & 18 & 24 & 30\\ 8 & 16 & 24 & 32 & 40\end{bmatrix}$$

Now, create the same matrix using `np.arange` (a useful function is `np.vstack([rowvector, newrow])`... look up its documentation):

Now slice the matrix you created to extract (i) just the second row, (ii) the central three entries in the second row, (iii) the first, third, and fifth elements in the third row

(9) Using just one line of code, generate the numbers corresponding to the sequence $1$, $\frac{1}{2^2}$, $\frac{1}{3^2}$, $\frac{1}{4^2}$, ... and so on until $\frac{1}{10^2}$

(10) With one line of code, generate a sequence of negative odd numbers starting at $-1$ and ending at $-19$. 